"use client";
import { useState } from "react";
import { Download, Plus, FileText, CheckCircle2, X } from "lucide-react";
import { useAuthStore } from "@/store/auth.store";
import { formatCurrency } from "@/lib/utils";
import { toast } from "sonner";

const PAYSLIPS = [
  { id: "1", month: "May 2025",   basic: 60000, allowances: 12000, bonus: 5000, pf: 4500, tax: 6000, deductions: 10500, net: 66500, status: "Paid" },
  { id: "2", month: "April 2025", basic: 60000, allowances: 12000, bonus: 0,    pf: 4500, tax: 6000, deductions: 10500, net: 61500, status: "Paid" },
  { id: "3", month: "March 2025", basic: 58000, allowances: 10000, bonus: 3000, pf: 4350, tax: 5800, deductions: 10150, net: 60850, status: "Paid" },
];

const EMPLOYEES_PAYROLL = [
  { id: "ep1", name: "Arjun Mehta",  dept: "Engineering", salary: 85000, status: "Generated", month: "May 2025", basic: 85000, allowances: 17000, bonus: 8500, pf: 6375, tax: 8500, deductions: 14875, net: 95625 },
  { id: "ep2", name: "Priya Sharma", dept: "HR",          salary: 72000, status: "Draft",     month: "May 2025", basic: 72000, allowances: 14400, bonus: 0,    pf: 5400, tax: 7200, deductions: 12600, net: 73800 },
  { id: "ep3", name: "Rahul Gupta",  dept: "Finance",     salary: 68000, status: "Generated", month: "May 2025", basic: 68000, allowances: 13600, bonus: 3400, pf: 5100, tax: 6800, deductions: 11900, net: 73100 },
  { id: "ep4", name: "Sneha Patel",  dept: "Design",      salary: 60000, status: "Paid",      month: "May 2025", basic: 60000, allowances: 12000, bonus: 5000, pf: 4500, tax: 6000, deductions: 10500, net: 66500 },
];

type PayrollEntry = typeof EMPLOYEES_PAYROLL[0];

/* ─── Payslip View Modal ─── */
function PayslipModal({ entry, onClose }: { entry: PayrollEntry; onClose: () => void }) {
  const handleDownload = () => {
    // Build a printable HTML string and open in new tab for PDF save
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Payslip - ${entry.name} - ${entry.month}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 700px; margin: 40px auto; color: #333; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .subtitle { color: #666; font-size: 13px; margin-bottom: 30px; }
    .row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee; }
    .section-title { font-weight: bold; font-size: 13px; text-transform: uppercase; letter-spacing: 0.05em; color: #888; margin: 20px 0 8px; }
    .net { display: flex; justify-content: space-between; padding: 14px 16px; background: #e8f5e9; border-radius: 8px; margin-top: 24px; font-size: 16px; font-weight: bold; }
    .net-amount { font-size: 22px; color: #22C55E; }
  </style>
</head>
<body>
  <h1>Payslip — ${entry.month}</h1>
  <div class="subtitle">Employee: ${entry.name} &bull; ${entry.dept} &bull; Generated by HR</div>

  <div class="section-title">Earnings</div>
  <div class="row"><span>Basic Salary</span><span>₹${entry.basic.toLocaleString()}</span></div>
  <div class="row"><span>Allowances</span><span>₹${entry.allowances.toLocaleString()}</span></div>
  <div class="row"><span>Bonus</span><span>₹${entry.bonus.toLocaleString()}</span></div>
  <div class="row" style="font-weight:bold"><span>Gross Salary</span><span style="color:#22C55E">₹${(entry.basic + entry.allowances + entry.bonus).toLocaleString()}</span></div>

  <div class="section-title">Deductions</div>
  <div class="row"><span>Provident Fund</span><span style="color:#EF4444">- ₹${entry.pf.toLocaleString()}</span></div>
  <div class="row"><span>Income Tax</span><span style="color:#EF4444">- ₹${entry.tax.toLocaleString()}</span></div>
  <div class="row" style="font-weight:bold"><span>Total Deductions</span><span style="color:#EF4444">- ₹${entry.deductions.toLocaleString()}</span></div>

  <div class="net">
    <span>Net Salary</span>
    <span class="net-amount">₹${entry.net.toLocaleString()}</span>
  </div>
</body>
</html>`;
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const w = window.open(url, "_blank");
    if (w) {
      setTimeout(() => { w.print(); URL.revokeObjectURL(url); }, 500);
    }
    toast.success(`Payslip for ${entry.name} opened for download!`);
  };

  return (
    <div style={{
      position: "fixed", inset: 0, background: "rgba(0,0,0,0.7)",
      display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1000,
    }} onClick={onClose}>
      <div className="card" style={{ padding: 32, width: 560, boxShadow: "var(--shadow-lg)", maxHeight: "90vh", overflowY: "auto" }}
        onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }}>
          <div>
            <div style={{ fontSize: 16, fontWeight: 700 }}>Payslip — {entry.month}</div>
            <div style={{ fontSize: 12, color: "var(--text-muted)", marginTop: 2 }}>{entry.name} · {entry.dept}</div>
          </div>
          <div style={{ display: "flex", gap: 8 }}>
            <button className="btn btn-secondary" style={{ gap: 6 }} onClick={handleDownload}>
              <Download size={14} /> Download PDF
            </button>
            <button className="btn btn-ghost" style={{ padding: "6px 8px" }} onClick={onClose}>
              <X size={16} />
            </button>
          </div>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 }}>
          {/* Earnings */}
          <div>
            <div style={{ fontSize: 12, fontWeight: 600, color: "var(--text-muted)", marginBottom: 12, letterSpacing: "0.05em", textTransform: "uppercase" }}>Earnings</div>
            {[
              { label: "Basic Salary",  value: formatCurrency(entry.basic) },
              { label: "Allowances",    value: formatCurrency(entry.allowances) },
              { label: "Bonus",         value: formatCurrency(entry.bonus) },
            ].map((item) => (
              <div key={item.label} style={{ display: "flex", justifyContent: "space-between", padding: "8px 0", borderBottom: "1px solid var(--border)" }}>
                <span style={{ fontSize: 13, color: "var(--text-secondary)" }}>{item.label}</span>
                <span style={{ fontSize: 13, fontWeight: 500 }}>{item.value}</span>
              </div>
            ))}
            <div style={{ display: "flex", justifyContent: "space-between", padding: "10px 0", marginTop: 4 }}>
              <span style={{ fontSize: 13, fontWeight: 600 }}>Gross Salary</span>
              <span style={{ fontSize: 13, fontWeight: 700, color: "var(--accent-green)" }}>{formatCurrency(entry.basic + entry.allowances + entry.bonus)}</span>
            </div>
          </div>

          {/* Deductions */}
          <div>
            <div style={{ fontSize: 12, fontWeight: 600, color: "var(--text-muted)", marginBottom: 12, letterSpacing: "0.05em", textTransform: "uppercase" }}>Deductions</div>
            {[
              { label: "Provident Fund", value: formatCurrency(entry.pf) },
              { label: "Income Tax",     value: formatCurrency(entry.tax) },
            ].map((item) => (
              <div key={item.label} style={{ display: "flex", justifyContent: "space-between", padding: "8px 0", borderBottom: "1px solid var(--border)" }}>
                <span style={{ fontSize: 13, color: "var(--text-secondary)" }}>{item.label}</span>
                <span style={{ fontSize: 13, fontWeight: 500, color: "var(--accent-red)" }}>- {item.value}</span>
              </div>
            ))}
            <div style={{ display: "flex", justifyContent: "space-between", padding: "10px 0", marginTop: 4 }}>
              <span style={{ fontSize: 13, fontWeight: 600 }}>Total Deductions</span>
              <span style={{ fontSize: 13, fontWeight: 700, color: "var(--accent-red)" }}>- {formatCurrency(entry.deductions)}</span>
            </div>
          </div>
        </div>

        {/* Net */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 20, padding: "16px 20px", background: "var(--accent-green-dim)", borderRadius: "var(--radius-sm)", border: "1px solid rgba(34,197,94,0.2)" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <CheckCircle2 size={18} color="var(--accent-green)" />
            <span style={{ fontSize: 15, fontWeight: 700 }}>Net Salary</span>
          </div>
          <span style={{ fontSize: 22, fontWeight: 800, color: "var(--accent-green)" }}>{formatCurrency(entry.net)}</span>
        </div>
      </div>
    </div>
  );
}

export default function PayrollPage() {
  const { role } = useAuthStore();
  const isAdmin = role === "super_admin" || role === "hr_admin";
  const [selected, setSelected] = useState<string | null>(null);
  const [viewEntry, setViewEntry] = useState<PayrollEntry | null>(null);

  const slip = PAYSLIPS.find((p) => p.id === selected) ?? PAYSLIPS[0];

  const handleGenerate = () => {
    toast.success("Payroll for May 2025 generated and dispatched successfully!");
  };

  const handleDownloadSlip = (entry: PayrollEntry) => {
    // Build printable HTML and open for PDF
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Payslip - ${entry.name} - ${entry.month}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 700px; margin: 40px auto; color: #333; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .subtitle { color: #666; font-size: 13px; margin-bottom: 30px; }
    .row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee; }
    .section-title { font-weight: bold; font-size: 13px; text-transform: uppercase; letter-spacing: 0.05em; color: #888; margin: 20px 0 8px; }
    .net { display: flex; justify-content: space-between; padding: 14px 16px; background: #e8f5e9; border-radius: 8px; margin-top: 24px; font-size: 16px; font-weight: bold; }
    .net-amount { font-size: 22px; color: #22C55E; }
  </style>
</head>
<body>
  <h1>Payslip — ${entry.month}</h1>
  <div class="subtitle">Employee: ${entry.name} &bull; ${entry.dept} &bull; Status: ${entry.status}</div>
  <div class="section-title">Earnings</div>
  <div class="row"><span>Basic Salary</span><span>₹${entry.basic.toLocaleString()}</span></div>
  <div class="row"><span>Allowances</span><span>₹${entry.allowances.toLocaleString()}</span></div>
  <div class="row"><span>Bonus</span><span>₹${entry.bonus.toLocaleString()}</span></div>
  <div class="row" style="font-weight:bold"><span>Gross</span><span>₹${(entry.basic + entry.allowances + entry.bonus).toLocaleString()}</span></div>
  <div class="section-title">Deductions</div>
  <div class="row"><span>PF</span><span>-₹${entry.pf.toLocaleString()}</span></div>
  <div class="row"><span>Tax</span><span>-₹${entry.tax.toLocaleString()}</span></div>
  <div class="net"><span>Net Salary</span><span class="net-amount">₹${entry.net.toLocaleString()}</span></div>
</body>
</html>`;
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const w = window.open(url, "_blank");
    if (w) setTimeout(() => { w.print(); URL.revokeObjectURL(url); }, 500);
    toast.success(`Payslip PDF for ${entry.name} opened for download!`);
  };


  return (
    <div className="page-container">
      {/* View Modal */}
      {viewEntry && <PayslipModal entry={viewEntry} onClose={() => setViewEntry(null)} />}

      <div className="page-header">
        <div>
          <h1 className="page-title">Payroll</h1>
          <p className="page-subtitle">{isAdmin ? "Generate and manage employee payslips" : "View your salary details and payslip history"}</p>
        </div>
        {isAdmin && (
          <button id="payroll-generate" className="btn btn-primary" style={{ gap: 6 }} onClick={handleGenerate}>
            <Plus size={14} /> Generate Payroll
          </button>
        )}
      </div>

      {isAdmin ? (
        <>
          {/* Stats */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 14, marginBottom: 24 }}>
            {[
              { label: "Total Payroll", value: "₹18.4L", sub: "May 2025", color: "var(--accent-purple)" },
              { label: "Generated",     value: "36",     sub: "payslips", color: "var(--accent-blue)"   },
              { label: "Paid",          value: "30",     sub: "employees",color: "var(--accent-green)"  },
              { label: "Pending",       value: "6",      sub: "to disburse", color: "var(--accent-amber)"},
            ].map((s) => (
              <div key={s.label} className="card" style={{ padding: "14px 18px" }}>
                <div style={{ fontSize: 22, fontWeight: 700, color: s.color, marginBottom: 4 }}>{s.value}</div>
                <div style={{ fontSize: 12, fontWeight: 500, color: "var(--text-secondary)", marginBottom: 2 }}>{s.label}</div>
                <div style={{ fontSize: 11, color: "var(--text-muted)" }}>{s.sub}</div>
              </div>
            ))}
          </div>

          <div className="table-container">
            <table>
              <thead>
                <tr>
                  <th>Employee</th><th>Department</th><th>Month</th><th>Salary</th><th>Status</th><th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {EMPLOYEES_PAYROLL.map((e) => (
                  <tr key={e.id}>
                    <td>
                      <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                        <div style={{ width: 30, height: 30, borderRadius: "50%", background: "var(--accent-blue-dim)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 600, color: "var(--accent-blue)" }}>
                          {e.name.split(" ").map((n) => n[0]).join("")}
                        </div>
                        <span style={{ fontWeight: 500, fontSize: 13 }}>{e.name}</span>
                      </div>
                    </td>
                    <td style={{ fontSize: 13, color: "var(--text-secondary)" }}>{e.dept}</td>
                    <td style={{ fontSize: 13, color: "var(--text-secondary)" }}>{e.month}</td>
                    <td style={{ fontWeight: 600 }}>{formatCurrency(e.salary)}</td>
                    <td>
                      <span className="badge" style={{
                        background: e.status === "Paid" ? "var(--accent-green-dim)" : e.status === "Generated" ? "var(--accent-blue-dim)" : "rgba(255,255,255,0.06)",
                        color: e.status === "Paid" ? "var(--accent-green)" : e.status === "Generated" ? "var(--accent-blue)" : "var(--text-muted)",
                      }}>{e.status}</span>
                    </td>
                    <td>
                      <div style={{ display: "flex", gap: 6 }}>
                        <button
                          className="btn btn-ghost"
                          style={{ padding: "4px 8px", fontSize: 12, gap: 4 }}
                          onClick={() => setViewEntry(e)}
                        >
                          <FileText size={12} /> View
                        </button>
                        <button
                          className="btn btn-ghost"
                          style={{ padding: "4px 8px", fontSize: 12, gap: 4 }}
                          onClick={() => handleDownloadSlip(e)}
                        >
                          <Download size={12} /> PDF
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      ) : (
        <div style={{ display: "grid", gridTemplateColumns: "260px 1fr", gap: 20 }}>
          {/* History list */}
          <div>
            <div style={{ fontSize: 13, fontWeight: 600, color: "var(--text-secondary)", marginBottom: 10 }}>Payslip History</div>
            <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
              {PAYSLIPS.map((p) => (
                <button key={p.id} onClick={() => setSelected(p.id)} style={{
                  display: "flex", justifyContent: "space-between", alignItems: "center",
                  padding: "12px 14px", borderRadius: "var(--radius-sm)", cursor: "pointer",
                  background: selected === p.id ? "var(--accent-blue-dim)" : "var(--bg-secondary)",
                  border: `1px solid ${selected === p.id ? "rgba(59,130,246,0.3)" : "var(--border)"}`,
                  transition: "all 0.15s", textAlign: "left",
                }}>
                  <div>
                    <div style={{ fontSize: 13, fontWeight: 500, color: "var(--text-primary)" }}>{p.month}</div>
                    <div style={{ fontSize: 12, color: "var(--text-muted)" }}>{formatCurrency(p.net)} net</div>
                  </div>
                  <span className="badge badge-green" style={{ fontSize: 10 }}>{p.status}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Payslip detail */}
          <div className="card" style={{ padding: 28 }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }}>
              <div>
                <div style={{ fontSize: 16, fontWeight: 700 }}>Payslip — {slip.month}</div>
                <div style={{ fontSize: 12, color: "var(--text-muted)", marginTop: 2 }}>Generated by HR · Credited on 1st</div>
              </div>
              <div style={{ display: "flex", gap: 8 }}>
                <button id="payslip-download" className="btn btn-secondary" style={{ gap: 6 }} onClick={() => {
                  const entry = { ...slip, id: slip.id, name: "My Payslip", dept: "Your Department" } as PayrollEntry;
                  handleDownloadSlip(entry);
                }}><Download size={14} /> Download PDF</button>
              </div>
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 }}>
              {/* Earnings */}
              <div>
                <div style={{ fontSize: 12, fontWeight: 600, color: "var(--text-muted)", marginBottom: 12, letterSpacing: "0.05em", textTransform: "uppercase" }}>Earnings</div>
                {[
                  { label: "Basic Salary",  value: formatCurrency(slip.basic) },
                  { label: "Allowances",    value: formatCurrency(slip.allowances) },
                  { label: "Bonus",         value: formatCurrency(slip.bonus) },
                ].map((item) => (
                  <div key={item.label} style={{ display: "flex", justifyContent: "space-between", padding: "8px 0", borderBottom: "1px solid var(--border)" }}>
                    <span style={{ fontSize: 13, color: "var(--text-secondary)" }}>{item.label}</span>
                    <span style={{ fontSize: 13, fontWeight: 500 }}>{item.value}</span>
                  </div>
                ))}
                <div style={{ display: "flex", justifyContent: "space-between", padding: "10px 0", marginTop: 4 }}>
                  <span style={{ fontSize: 13, fontWeight: 600 }}>Gross Salary</span>
                  <span style={{ fontSize: 13, fontWeight: 700, color: "var(--accent-green)" }}>{formatCurrency(slip.basic + slip.allowances + slip.bonus)}</span>
                </div>
              </div>

              {/* Deductions */}
              <div>
                <div style={{ fontSize: 12, fontWeight: 600, color: "var(--text-muted)", marginBottom: 12, letterSpacing: "0.05em", textTransform: "uppercase" }}>Deductions</div>
                {[
                  { label: "Provident Fund", value: formatCurrency(slip.pf) },
                  { label: "Income Tax",     value: formatCurrency(slip.tax) },
                ].map((item) => (
                  <div key={item.label} style={{ display: "flex", justifyContent: "space-between", padding: "8px 0", borderBottom: "1px solid var(--border)" }}>
                    <span style={{ fontSize: 13, color: "var(--text-secondary)" }}>{item.label}</span>
                    <span style={{ fontSize: 13, fontWeight: 500, color: "var(--accent-red)" }}>- {item.value}</span>
                  </div>
                ))}
                <div style={{ display: "flex", justifyContent: "space-between", padding: "10px 0", marginTop: 4 }}>
                  <span style={{ fontSize: 13, fontWeight: 600 }}>Total Deductions</span>
                  <span style={{ fontSize: 13, fontWeight: 700, color: "var(--accent-red)" }}>- {formatCurrency(slip.deductions)}</span>
                </div>
              </div>
            </div>

            {/* Net */}
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 20, padding: "16px 20px", background: "var(--accent-green-dim)", borderRadius: "var(--radius-sm)", border: "1px solid rgba(34,197,94,0.2)" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <CheckCircle2 size={18} color="var(--accent-green)" />
                <span style={{ fontSize: 15, fontWeight: 700 }}>Net Salary</span>
              </div>
              <span style={{ fontSize: 22, fontWeight: 800, color: "var(--accent-green)" }}>{formatCurrency(slip.net)}</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
